/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regionfinder;

import javax.swing.JOptionPane;

/**
 *
 * @author Roel
 */
public class RegionFinderForm extends javax.swing.JFrame {

    /**
     * Creates new form RegoinFinderForm
     */
    public RegionFinderForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNS = new javax.swing.JLabel();
        intNSCoordinateInput = new javax.swing.JTextField();
        lblNSCoordinate = new javax.swing.JLabel();
        lblEW = new javax.swing.JLabel();
        intEWCoordinateInput = new javax.swing.JTextField();
        lblEWCoordinate = new javax.swing.JLabel();
        bttnCalculate = new javax.swing.JButton();
        bttnReset = new javax.swing.JButton();
        bttnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblRFName = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();
        comboNS = new javax.swing.JComboBox<>();
        comboEW = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Region Finder");
        setMinimumSize(new java.awt.Dimension(806, 411));
        setResizable(false);

        lblNS.setText("North/South");

        intNSCoordinateInput.setText("0");
        intNSCoordinateInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                intNSCoordinateInputKeyTyped(evt);
            }
        });

        lblNSCoordinate.setText("N/S Coordinate");

        lblEW.setText("East/West");

        intEWCoordinateInput.setText("0");
        intEWCoordinateInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                intEWCoordinateInputKeyTyped(evt);
            }
        });

        lblEWCoordinate.setText("E/W Coordinate");

        bttnCalculate.setText("Calculate Region Location");
        bttnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCalculateActionPerformed(evt);
            }
        });

        bttnReset.setText("Reset");
        bttnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnResetActionPerformed(evt);
            }
        });

        bttnExit.setText("Exit");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        lblRFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRFName.setText("Region File Name");

        lblOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutput.setToolTipText("");
        lblOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblOutput.setMaximumSize(new java.awt.Dimension(300, 35));
        lblOutput.setMinimumSize(new java.awt.Dimension(300, 35));
        lblOutput.setName(""); // NOI18N
        lblOutput.setPreferredSize(new java.awt.Dimension(300, 35));

        comboNS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North", "South" }));

        comboEW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "East", "West" }));

        jLabel1.setText("Coded/Created by Newbeaveteran");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("7 Days to Die Region Finder");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNS)
                                    .addComponent(lblEW))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bttnExit)
                                        .addGap(18, 18, 18)
                                        .addComponent(bttnReset)
                                        .addGap(18, 18, 18)
                                        .addComponent(bttnCalculate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboNS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboEW, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEWCoordinate)
                                            .addComponent(lblNSCoordinate))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(intNSCoordinateInput)
                                            .addComponent(intEWCoordinateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRFName)
                                .addGap(27, 27, 27)
                                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNS)
                                .addGap(37, 37, 37)
                                .addComponent(lblEW))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNSCoordinate)
                                    .addComponent(intNSCoordinateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(intEWCoordinateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEWCoordinate)
                                    .addComponent(comboEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCalculate)
                            .addComponent(bttnReset)
                            .addComponent(bttnExit))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblRFName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCalculateActionPerformed
       //Initializers
        int num1, num2;
        String NS, EW, Answer;
        
        //Try Catch
        try
        {
            if (this.intEWCoordinateInput.getText().equals("")){
                this.intEWCoordinateInput.setText("0");
            }
            
            if (this.intNSCoordinateInput.getText().equals("")){
                this.intNSCoordinateInput.setText("0");
            }
            num1 = Integer.parseInt(this.intNSCoordinateInput.getText());
            num2 = Integer.parseInt(this.intEWCoordinateInput.getText());
            NS = String.valueOf(this.comboNS.getSelectedItem());
            EW = String.valueOf(this.comboEW.getSelectedItem());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Conditions and Formulas
        
        //East and West Calculation
        if (EW.equals("East"))
        {
            Answer = "r."+String.valueOf(num2/512)+".";
        }
        
        else
        {
            if (num2/512==0)
            {
                Answer = "r.-"+String.valueOf((num2/512)+1)+".";
            }else
            {
                Answer = "r.-"+String.valueOf((num2/512)+1)+".";
            }
            
        }
        
        //North and South Calculation
        if(NS.equals("North"))
        {
            Answer+=String.valueOf(num1/512)+".7rg";
        }
        else
        {
            if(num1/512==0)
            {
                Answer+="-"+String.valueOf((num1/512)+1)+".7rg";
            }else{
                Answer+="-"+String.valueOf((num1/512)+1)+".7rg";
            }
            
        }
        this.lblOutput.setText(Answer);
            
    }//GEN-LAST:event_bttnCalculateActionPerformed

    private void intNSCoordinateInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intNSCoordinateInputKeyTyped
        char vchar = evt.getKeyChar(); 
        if(!(Character.isDigit(vchar)))
            evt.consume();
    }//GEN-LAST:event_intNSCoordinateInputKeyTyped

    private void intEWCoordinateInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intEWCoordinateInputKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)))
            evt.consume();
    }//GEN-LAST:event_intEWCoordinateInputKeyTyped

    private void bttnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnResetActionPerformed
        this.comboEW.setSelectedIndex(0);
        this.comboNS.setSelectedIndex(0);
        this.intEWCoordinateInput.setText("0");
        this.intNSCoordinateInput.setText("0");
    }//GEN-LAST:event_bttnResetActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegionFinderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegionFinderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegionFinderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegionFinderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegionFinderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCalculate;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnReset;
    private javax.swing.JComboBox<String> comboEW;
    private javax.swing.JComboBox<String> comboNS;
    private javax.swing.JTextField intEWCoordinateInput;
    private javax.swing.JTextField intNSCoordinateInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEW;
    private javax.swing.JLabel lblEWCoordinate;
    private javax.swing.JLabel lblNS;
    private javax.swing.JLabel lblNSCoordinate;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblRFName;
    // End of variables declaration//GEN-END:variables
}
